"""empty message

Revision ID: 992050240c9c
Revises: 
Create Date: 2022-09-08 11:02:02.324185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '992050240c9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('public_catalogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stac_version', sa.Text(), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stac_ingestion_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_started', sa.DateTime(), nullable=True),
    sa.Column('time_finished', sa.DateTime(), nullable=True),
    sa.Column('source_stac_api_url', sa.Text(), nullable=True),
    sa.Column('target_stac_api_url', sa.Text(), nullable=True),
    sa.Column('update', sa.Boolean(), nullable=True),
    sa.Column('newly_stored_collections_count', sa.Integer(), nullable=True),
    sa.Column('newly_stored_collections', sa.Text(), nullable=True),
    sa.Column('updated_collections_count', sa.Integer(), nullable=True),
    sa.Column('updated_collections', sa.Text(), nullable=True),
    sa.Column('newly_stored_items_count', sa.Integer(), nullable=True),
    sa.Column('updated_items_count', sa.Integer(), nullable=True),
    sa.Column('already_stored_items_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('public_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('stored_search_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('associated_catalog_id', sa.Integer(), nullable=False),
    sa.Column('used_search_parameters', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['associated_catalog_id'], ['public_catalogs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stored_search_parameters')
    op.drop_table('user')
    op.drop_table('stac_ingestion_status')
    op.drop_table('public_catalogs')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
